#!/bin/sh
echo "Sincronizando la version Lite automaticamente (pre-commit hook)..."
powershell.exe -ExecutionPolicy Bypass -File "sync-lite.ps1"
if [ $? -ne 0 ]; then
    echo "Error al ejecutar sync-lite.ps1. Abortando commit."
    exit 1
fi

# Añadir los archivos sincronizados al commit actual
git add lite/
exit 0
